# Generated by Django 5.0.4 on 2024-04-30 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculators.calculator')),
            ],
        ),
    ]
