# Generated by Django 5.0.4 on 2024-04-30 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='URL',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
