# Generated by Django 4.1 on 2024-05-02 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calculators", "0003_solution_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solution",
            name="calculator",
        ),
    ]
