# Generated by Django 4.1 on 2024-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculators", "0005_alter_solution_url_alter_solution_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="URL",
            field=models.URLField(),
        ),
    ]
